### ISSUE TITLE
Upgrade to HomeBridge Version 1.3.9

### ISSUE THREAD

**Issue by KAEL10** [Apollon77/homebridge-plugin-wrapper#26]
Moin Moin,

ich probiere hier einmal jetzt auf diesem Wege mein Glück.
Ich probiere jetzt seit geraumer Zeit das HomeBridge PlugIn "Homebridge-govee" über den Wrapper zum laufen zu bekommen.
Mal passiert einfach gar nichts und manchmal taucht im Log die Fehlermeldung auf, dass HomeBridge in Version 1.3.4 vorliegt, das Plugin aber Version 1.3.9 benötigt.

![Error-Log](https://user-images.githubusercontent.com/96777109/150829490-3159a488-37bb-4d9d-b5c1-80a1218890e4.png)

Jetzt habe ich schon einfach mal probiert stumpf über Homebridge-version.js die Version zu ändern. Hat scheinbar keine Auswirkung. Zumindest war die Fehlermeldung anschließend unverändert.

Der Adapter selber scheint zu laufen, da ich eine Eufy PlugIn schon erfolgreich in Betrieb habe.

Laut Change-Log von diesem Adapter wurde zuletzt die Homebridge Version auf 1.3.4 angehoben. Ist das eventuell jetzt wieder mit Version 1.3.9 möglich?

Falsch das an dieser Stelle falsch aufgehoben ist und das eher in ein Forum oder dergleichen gehört: Bitte löschen.

Besten Dank schon einmal! : )

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 4.0.2
 - JS-Controller version: 3.3.22
 - Node version: 14.18.3

**Comment by Apollon77** [comment]
Der Plan war auf die 1.4.0 zu warten bis isch wieder alles update ... mal schauen ob ich vorher zeit finde. Ich habe keine Idee warum jemand unbedingt homebridge 1.3.9 "Braucht" ... Da ist nur ein Bugfiel mit nodejs 17 drin ... da macht es der Plugin Dev gerade unnötig schwer für die User .. aber naja ...

**Comment by KAEL10** [comment]
Alles klar. Danke für die Rückmeldung!
Aber keinen Stress, bei mir ist keine Gefahr im Verzug. 😄 Dann schiebe ich das Projekt erstmal nach hinten bevor ich da weiter experimentiere. 
Im Zweifel warte ich halt auf 1.4.1.

**Comment by Apollon77** [comment]
Github is now on 1.4.1. Release most likely later today
